[package]
name = "site-discovery-flea"
version = "1.0.0"
authors = ["Eugene Lebedev <duke.tougu@gmail.com>"]
edition = "2018"

[profile.release]
opt-level = 'z'
lto = true
codegen-units = 1
panic = 'abort'

[dependencies]
log = "0.4"
log4rs = "0.8.3"
